# -*- coding: utf-8 -*-
"""Копия блокнота "AI_teacher_v1.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10l6LK6cAOvw6KiNAYLJF2wcWryiWm-Oa

## Система AI-учителя
"""

pip install openai==0.27

pip install ipywidgets

from google.colab import userdata

from IPython.display import display, Markdown, HTML
import ipywidgets as widgets
import openai
from datetime import datetime


class ColabTeacher:
    def __init__(self, api_key=None):
        self.api_key = api_key
        if api_key:
            openai.api_key = api_key
        self.create_widgets()
        self.conversation_history = []

    def create_widgets(self):
        # Поле ввода вопроса
        self.question_input = widgets.Textarea(
            placeholder='Введите ваш вопрос...',
            layout={'width': '600px', 'height': '50px'}
        )

        # Добавляем обработчик клавиши Enter
        self.question_input.observe(self.handle_keypress, names='value')

        # Кнопка отправки
        self.submit_button = widgets.Button(
            description='Задать вопрос',
            button_style='primary',
            layout={'width': 'auto', 'margin': '10px 0'}
        )
        self.submit_button.on_click(self.handle_question)

        # Область вывода
        self.output_area = widgets.Output()

    def handle_keypress(self, change):
        if change.new.endswith('\n'):
            # Очищаем поле ввода сразу
            question = change.new.rstrip()  # Убираем последний перенос строки
            self.question_input.value = ''

            # Если вопрос не пустой (кроме пробелов и переносов строк), обрабатываем его
            if question.strip():
                self.process_question(question)

    def display_interface(self):
        display(HTML("""
            <div style="margin: 20px 0;">
                <h2>🤖 AI-учитель</h2>
                <p style="color: #666;">
                    Enter — отправить вопрос<br>
                    Shift+Enter — перенос строки
                </p>
            </div>
        """))

        display(self.question_input)
        display(self.submit_button)
        display(self.output_area)

    def handle_question(self, _):
        question = self.question_input.value
        if question.strip():
            self.question_input.value = ''
            self.process_question(question)

    def process_question(self, question):
        try:
            current_time = datetime.now().strftime("%d.%m.%Y %H:%M")

            self.conversation_history.append({
                "role": "user",
                "content": question,
                "time": current_time
            })


            # TODO: написать промпт
            prompt = "Ты - AI-учитель, помогающий изучать основы искусственного интеллекта."

            response = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": prompt},
                    *[{"role": msg["role"], "content": msg["content"]} for msg in self.conversation_history]
                ]
            )

            answer = response.choices[0].message.content
            self.conversation_history.append({
                "role": "assistant",
                "content": answer,
                "time": current_time
            })

            self.output_area.clear_output()

            # Добавляем все сообщения в обратном порядке
            with self.output_area:
                for i in range(len(self.conversation_history)-1, -1, -2):
                    if i >= 1:  # Проверяем, что есть пара вопрос-ответ
                        q = self.conversation_history[i-1]["content"]
                        a = self.conversation_history[i]["content"]
                        time = self.conversation_history[i]["time"]

                        # Определяем стили для текущего блока
                        if i == len(self.conversation_history) - 1:
                            border_color = "#007bff"  # Синий для последнего ответа
                            time_color = "#007bff"
                        else:
                            border_color = "#6c757d"  # Серый для старых ответов
                            time_color = "#6c757d"

                        display(HTML(f"""
                            <div style="margin: 20px 0; border-left: 3px solid {border_color};">
                                <!-- Вопрос -->
                                <div style="padding: 10px; background-color: #f8f9fa; margin-bottom: 1px;">
                                    {q.replace(chr(10), '<br>')}
                                </div>

                                <!-- Ответ -->
                                <div style="padding: 10px; background-color: #ffffff;">
                                    {a.replace(chr(10), '<br>')}
                                    <div style="margin-top: 10px; font-size: 0.8em; color: {time_color};">
                                        {time}
                                    </div>
                                </div>
                            </div>
                        """))

        except Exception as e:
            with self.output_area:
                display(HTML(f"""
                    <div style="color: #dc3545; margin: 10px 0;">
                        ❌ Произошла ошибка: {str(e)}
                    </div>
                """))

# TODO: Составляем программу обучения

# TODO: сохранять состояние между уроками = перенос данных в новый ноутбук
# - в ноутбуке
# - в файле
# - онлайн (Google Drive)

# TODO: способность задавать проверочные вопросы
# - создавать задания для ученика
# - давать возможность их выполнить и предъявить решение и ответ
# - проверить и написать отзыв для ученика

# TODO: способность приводить примеры кода, которые можно запускать
# TODO: графики (matplotlib, Plotly...)

# TODO: дать возможность скачать результаты

# TODO: в будущем
# - Улучить интерфейс - "думаю..." и т.д.
# - Выводить ответы, отформатированные красиво, например, образцы кода
# - Что сохраняем между уроками:
#   - Программа обучения
#   - Прогресс
#       - Выполненыые задания
#       - Частые ошибки
#       - ...
#   - Сведения об ученике: уровень, стиль общения...

"""## Разговор с AI-учителем"""

teacher = ColabTeacher(userdata.get('OPENAI_API_KEY'))
teacher.display_interface()

my_list = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]
sorted_list = sorted(my_list)
print(sorted_list)

text = """
Использование метода `sorted()` для создания нового отсортированного списка:

```python
my_list = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]
sorted_list = sorted(my_list)
print(sorted_list)
```

Использование метода `sort()` для сортировки списка на месте (не создает новый отсортированный список):

```python
my_list = [3, 1, 4, 1, 5, 9, 2]
my_list.sort()
print(my_list)
```
"""

display(Markdown(text))